### ISSUE TITLE
Random xls updates mess with actual postings

### ISSUE THREAD

**Issue by madchap** [madchap/energiapro_gas_consumption#2]
Some days, there may be more than 1 posting from the LoraWan device to mothership. When this happens, the concerned line in the XLS file gets updated, not appended to. Currently, the script looks only at the last line.

It appears that the updated record is made as the new line is also gets posted, resulting in a changed second-to-last record and the last record.

In the end, and as the XLS file is changing its state whenever, it's not really possible to correlate what gets posted in HA and what we can see in the XLS file on a daily basis.

Example:
Posted in Energy dashboard Dec 1st morning.
![image](https://user-images.githubusercontent.com/5468769/205006486-d7c4bfbf-6b05-44fe-b7d7-7991b9e9bd46.png)

From the XLS file download on Dec 1st at 9am.
![image](https://user-images.githubusercontent.com/5468769/205006564-222141c2-8319-4a43-a7cf-b90455b5c574.png)

The 6.21 and the 7940 never got posted, and the result is a jump of 9m3.

![image](https://user-images.githubusercontent.com/5468769/205006822-21694566-9bfc-47d5-b62a-26a57fe074bb.png)

![image](https://user-images.githubusercontent.com/5468769/205006871-4aacc8d7-cb7a-4956-b357-9de1e8531db0.png)

There is a plain miss on posting the daily value of 6.21.

This may require way more gymnastic to work around their crappy handling of data posting.

**Comment by madchap** [comment]
Or just post once a day for the previous day? (currently the app will run every hour)

**Comment by madchap** [comment]
2 actual postings, which get rolled up on the next xls update, making numbers wrong:

![image](https://user-images.githubusercontent.com/5468769/205429967-f6efd58c-de0d-48a7-a9f3-a2730147d26a.png)

and

![image](https://user-images.githubusercontent.com/5468769/205429980-f33e1688-1b55-43f8-aea4-7ff30a72db80.png)

The next day, roll up on the XLS without preserving anything yields an extra datapoint which screws up the data.

![image](https://user-images.githubusercontent.com/5468769/205430008-a2361923-b312-476c-b48b-34a7fcd7cdef.png)

![image](https://user-images.githubusercontent.com/5468769/205430014-303d526d-fed4-48ec-bd39-0870dba638f7.png)

**Comment by madchap** [comment]
The latest [commit](https://github.com/madchap/energiapro_gas_consumption/commit/4dc852b797466d05519a72b719efc8290faf4c3c) at the time of this writing will have the appdaemon run at 10am local time (presumably, we're all in the same TZ).

99% of the time, posting happen before then. It does not seem to be 100% reliable. Some day (e.g at least a Saturday) they don't happen, but well.

**Comment by DaveLeonard** [comment]
This issue concern only the 2 most recent values and  should have been addressed Energiapro-side by increasing the number of times the consolidation run daily in the databases.

Customers' LoraWan normal behavior should send 2 daily updates to datacenters. Previously, consolidation happened 2 times a day, so depending on the datetime the impulse hit the database,  it can be processed and consolidated the next day, which show changing data for the 2 last days.

Keep me updated if it's not the case.

**Comment by madchap** [comment]
It seems that it works better now indeed, checked on the last 3 days, values match. Thanks @DaveLeonard :)

Next is to see how we could ensure that data from Energiapro-side could be append-only and never upserted, to ensure downstream systems never doubt the state of the data, especially as you build the API facade. This would then fix the problem of representing data with a lag of 1 day (today, we can only post the on day n for day n-1, but we should be able to query every hour for example, and just get whatever increment in value, whenever it happens and let downstream system deal with it).
