### ISSUE TITLE
Another change throwing off XSS

### ISSUE THREAD

**Issue by madchap** [madchap/energiapro_gas_consumption#7]
Some recent change throwing things off? or a random bug?

![image](https://user-images.githubusercontent.com/5468769/210558704-dbde55e1-dfa7-48f3-a577-cba6d059f219.png)

**Comment by widgetfonda** [comment]
Same here!

Home Assistant updated yesterday.

Home Assistant 2022.12.9
Supervisor 2022.12.1
Operating System 9.4
Interface utilisateur : 20221213.1 - latest 

![energia](https://user-images.githubusercontent.com/2279323/210566456-e428cb00-3a91-4619-a7c1-65a1673f0aca.png)

**Comment by madchap** [comment]
Will take a look tonight hopefully - I have pressure now, people using my stuff ;-)

**Comment by widgetfonda** [comment]
Yes indeed you have pressure now 😉

Your integration is a must have for my home automation system. The best thing would be if Holdigaz would provide an API to simplify things, but I don't know if it's in their plans.

**Comment by madchap** [comment]
Yea, I am talking with them right now, I should be in their beta testers list whenever their first API draft comes out.

**Comment by widgetfonda** [comment]
This is great news! I can't wait to see the future progress.
